<h1>Zend Framework "Form Decorator" for dijit.TitlePane</h1>
<?php echo $this->form ?>
<?php
    $this->dojo()->enable()
                 ->requireModule('dojox.validate.regexp');
?>
<h5 class="highlightCodeHeading">Code in View:</h5>
<div class="highlightCode">
    <?php echo $this->code ?>
</div>
<h5 class="highlightCodeHeading">Code for the Dojo Form:</h5>
<div class="highlightCode">
    <?php echo $this->formCode ?>
</div>
