<h1>New Dojo Components for Zend Framework</h1>
<div id="programmatic">
    <h2 class="center">Dijits will be created with <u>Programmatic method - Zend_Dojo_View_Helper_Dojo::setUseProgrammatic();</u></h2>
    <h3>Form Decorator and View Helper for <u>dijit.TitlePane</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'simple')) ?>" title="Example of the widget dijit.TitlePane (Simple)">Example of the widget <strong>dijit.TitlePane</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'remote-content')) ?>" title="Example of the widget dijit.TitlePane with remote content">Example of the widget <strong>dijit.TitlePane</strong> with remote content</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'subforms-decorator')) ?>" title="Example of the widget dijit.TitlePane as decorator for subforms">Example of the widget <strong>dijit.TitlePane</strong> as decorator for subforms</a>
        </li>
    </ul>
    <h3>Form Element and View Helper for <u>dijit.form.select</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'simple')) ?>" title="Example of the widget dijit.form.Select (Simple)">Example of the widget <strong>dijit.form.Select</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'data-store')) ?>" title="Example of the widget dijit.form.Select with enabled Data Store - dojo.data.ItemFileReadStore">Example of the widget <strong>dijit.form.Select</strong> with enabled <strong>Data Store - dojo.data.ItemFileReadStore</strong></a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'select-form')) ?>" title="Example of the widget dijit.form.Select as Dojo Form Element">Example of the widget <strong>dijit.form.Select</strong> as Dojo Form Element</a>
        </li>
    </ul>
    <h3>Form Decorator and View Helper for <u>dijit.Tooltip</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-tooltip', 'action' => 'simple')) ?>" title="Example of the widget dijit.Tooltip (Simple)">Example of the widget <strong>dijit.Tooltip</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-tooltip', 'action' => 'tooltip-decorator')) ?>" title="Example of the widget dijit.Tooltip as Dojo Form Element Decorator">Example of the widget <strong>dijit.Tooltip</strong> as Dojo Form Element Decorator</a>
        </li>
    </ul>
    <h3>Form Decorator and View Helper for <u>dijit.Dialog</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'simple')) ?>" title="Example of the widget dijit.Dialog (Simple)">Example of the widget <strong>dijit.Dialog</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'remote-content')) ?>" title="Example of the widget dijit.Dialog with remote content">Example of the widget <strong>dijit.Dialog</strong> with remote content</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'form-in-dialog')) ?>" title="Example of the widget dijit.Dialog with Dojo Form">Example of the widget <strong>dijit.Dialog</strong> with Dojo Form</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'dialog-decorator')) ?>" title="Example of the widget dijit.Dialog as Dojo Form Decorator">Example of the widget <strong>dijit.Dialog</strong> as Dojo Form Decorator</a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.ProgressBar</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-progress-bar', 'action' => 'simple')) ?>" title="Example of the widget dijit.ProgressBar">Example of the widget <strong>dijit.ProgressBar</strong></a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.form.DropDownButton</u> widget and View Helper for <u>dijit.TooltipDialog</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-drop-down-button', 'action' => 'simple')) ?>" title="Example of the widget dijit.form.DropDownButton and View Helper for dijit.TooltipDialog">Example of the widget <strong>dijit.form.DropDownButton</strong> and View Helper for <strong>dijit.TooltipDialog</strong></a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.ColorPalette</u> widget and Form Element for <u>dijit.form.DropDownButton</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-color-palette', 'action' => 'simple')) ?>" title="Example of the widget dijit.ColorPalette (Simple)">Example of the widget <strong>dijit.ColorPalette</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-color-palette', 'action' => 'palette-in-form')) ?>" title="Example of the widget dijit.ColorPalette with Dojo Form and Form Element for dijit.form.DropDownButton widget">Example of the widget <strong>dijit.ColorPalette</strong> with Dojo Form and Form Element for <strong>dijit.form.DropDownButton</strong> widget</a>
        </li>
    </ul>
</div>
<hr id="programmatic-declarative-separator" />
<div id="declarative">
    <h2 class="center">Dijits will be created with <u>Declarative method - Zend_Dojo_View_Helper_Dojo::setUseDeclarative();</u></h2>
    <h3>Form Decorator and View Helper for <u>dijit.TitlePane</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.TitlePane (Simple)">Example of the widget <strong>dijit.TitlePane</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'remote-content', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.TitlePane with remote content">Example of the widget <strong>dijit.TitlePane</strong> with remote content</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-title-pane', 'action' => 'subforms-decorator', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.TitlePane as decorator for subforms">Example of the widget <strong>dijit.TitlePane</strong> as decorator for subforms</a>
        </li>
    </ul>
    <h3>Form Element and View Helper for <u>dijit.form.select</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.form.Select (Simple)">Example of the widget <strong>dijit.form.Select</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'data-store', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.form.Select with enabled Data Store - dojo.data.ItemFileReadStore">Example of the widget <strong>dijit.form.Select</strong> with enabled <strong>Data Store - dojo.data.ItemFileReadStore</strong></a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-select', 'action' => 'select-form', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.form.Select as Dojo Form Element">Example of the widget <strong>dijit.form.Select</strong> as Dojo Form Element</a>
        </li>
    </ul>
    <h3>Form Decorator and View Helper for <u>dijit.Tooltip</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-tooltip', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Tooltip (Simple)">Example of the widget <strong>dijit.Tooltip</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-tooltip', 'action' => 'tooltip-decorator', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Tooltip as Dojo Form Element Decorator">Example of the widget <strong>dijit.Tooltip</strong> as Dojo Form Element Decorator</a>
        </li>
    </ul>
    <h3>Form Decorator and View Helper for <u>dijit.Dialog</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Dialog (Simple)">Example of the widget <strong>dijit.Dialog</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'remote-content', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Dialog with remote content">Example of the widget <strong>dijit.Dialog</strong> with remote content</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'form-in-dialog', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Dialog with Dojo Form">Example of the widget <strong>dijit.Dialog</strong> with Dojo Form</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-dialog', 'action' => 'dialog-decorator', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.Dialog as Dojo Form Decorator">Example of the widget <strong>dijit.Dialog</strong> as Dojo Form Decorator</a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.ProgressBar</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-progress-bar', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.ProgressBar">Example of the widget <strong>dijit.ProgressBar</strong></a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.form.DropDownButton</u> widget and View Helper for <u>dijit.TooltipDialog</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-form-drop-down-button', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.form.DropDownButton and View Helper for dijit.TooltipDialog">Example of the widget <strong>dijit.form.DropDownButton</strong> and View Helper for <strong>dijit.TooltipDialog</strong></a>
        </li>
    </ul>
    <h3>View Helper for <u>dijit.ColorPalette</u> widget and Form Element for <u>dijit.form.DropDownButton</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-color-palette', 'action' => 'simple', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.ColorPalette (Simple)">Example of the widget <strong>dijit.ColorPalette</strong> (Simple)</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-color-palette', 'action' => 'palette-in-form', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.ColorPalette with Dojo Form and Form Element for dijit.form.DropDownButton widget">Example of the widget <strong>dijit.ColorPalette</strong> with Dojo Form and Form Element for <strong>dijit.form.DropDownButton</strong> widget</a>
        </li>
    </ul>
    <h3>Form Decorator for <u>dijit.TooltipDialog</u> widget:</h3>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'dijit-tooltip-dialog', 'action' => 'tooltip-dialog-decorator', 'useDeclarative' => '1')) ?>" title="Example of the widget dijit.TooltipDialog as Dojo Form Decorator">Example of the widget <strong>dijit.TooltipDialog</strong> as Dojo Form Decorator</a>
        </li>
    </ul>
</div>
