<h1>Zend Framework "Form Decorator" for dijit.TooltipDialog</h1>
<h2><u>dijit.TooltipDialog</u> as Form's Decorator:</h2>
<?php
    $this->dojo()->enable()
                 ->requireModule('dojox.validate.regexp');
?>
<?php echo $this->form ?>
<br />
<p>
    When pressing this button the Dojo Form with <u>dijit.TooltipDialog</u> Decorator will popup.
</p>
<?php echo $this->dropDownButton(
    'dropDownButton-1',
    'Show Form with dijit.TooltipDialog Decorator',
    array(
        'label'    => 'Show Form with dijit.TooltipDialog Decorator',
        'dropDown' => 'tooltipDialogExample'
    ),
    array(
    )
) ?>
<h5 class="highlightCodeHeading">Code in View:</h5>
<div class="highlightCode">
    <?php echo $this->code ?>
</div>
<h5 class="highlightCodeHeading">Code for the Dojo Form:</h5>
<div class="highlightCode">
    <?php echo $this->formCode ?>
</div>
