<h1>Zend Framework "Form Element Decorator" for dijit.Tooltip</h1>
<h2>For every Form's element with title defined is popup dijit.Tooltip:</h2>
<br />
<?php
    $this->dojo()->enable()
                 ->requireModule('dojox.validate.regexp');
?>
<?php echo $this->form ?>
<h5 class="highlightCodeHeading">Code in View:</h5>
<div class="highlightCode">
    <?php echo $this->code ?>
</div>
<h5 class="highlightCodeHeading">Code for the Dojo Form:</h5>
<div class="highlightCode">
    <?php echo $this->formCode ?>
</div>
