<h1>Zend Framework "View Helper" for dijit.Dialog - Simple Usage</h1>
<h2>Content was defined in the view:</h2>
<?php echo $this->dialog(
    'dialog-1',
    '<p>Lorem ipsum dolor sit amet consectetuer natoque euismod laoreet sit Aliquam. Pretium Vestibulum Praesent '
  . 'orci ipsum tempor eros iaculis Nulla nulla nibh. Lacus sollicitudin malesuada sem Vivamus sociis Donec malesuada '
  . 'quis ipsum eget. Sem Pellentesque eget Sed in Ut elit interdum porttitor commodo laoreet. Curabitur sociis '
  . 'suscipit elit Donec In nec rhoncus nunc ipsum felis. Faucibus Suspendisse at Nulla in Donec ante justo.</p>'
  . '<p>Consequat Quisque Suspendisse Pellentesque Suspendisse eget tortor sit odio elit turpis. Id ac est congue '
  . 'ligula interdum Lorem magna nisl id condimentum. Feugiat elit massa Quisque risus nunc amet felis urna congue '
  . 'ante. Ac convallis quis lobortis ut Aenean quis consectetuer elit urna adipiscing. Porttitor est dui nibh '
  . 'pharetra dictum ipsum a libero porttitor elit. At metus quis eu tempus sodales laoreet Phasellus sed dis rutrum. '
  . 'Tortor eget tempor fringilla gravida vitae leo tincidunt Vestibulum parturient.</p>'
  . '<p>Nec nascetur tempus elit neque pretium mus augue lobortis est non. Tempus vitae laoreet dolor Nulla '
  . 'Vestibulum id lorem egestas semper massa. Wisi ornare Suspendisse Curabitur at ut convallis volutpat turpis '
  . 'Curabitur consequat. Lacinia ut at elit tincidunt congue tristique Suspendisse tortor consequat pretium. Augue '
  . 'elit quis id pede risus accumsan nunc enim pulvinar ante. Pede sed ac est hendrerit pellentesque vitae id elit '
  . 'adipiscing Sed. Semper tempor.</p>',
    array(
        'title' => 'dijit.Dialog example 1',
        'jsId'  => 'dialog1'
    ),
    array(
    )
) ?>
<br />
<p>
    When pressing this button the dialog will popup.
</p>
<?php echo $this->button(
    'show-dialog-1',
    'Show Dialog 1',
    array(
        'onClick' => 'showDialog1();'
    ),
    array(
        'title' => 'After click Dialog 1 will be showed',
        'style' => 'margin-top: 10px;'
    )
) ?>
<?php $this->inlineScript()->captureStart() ?>
function showDialog1() {
    dialog1.show();
}
<?php $this->inlineScript()->captureEnd() ?>
<h5 class="highlightCodeHeading">Code in View:</h5>
<div class="highlightCode">
    <?php echo $this->code ?>
</div>
